kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  namespace: default
  name: reviews
  labels:
    kiali_wizard: request_routing
  annotations: ~
spec:
  host: reviews.default.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
  trafficPolicy: ~

---

kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  namespace: default
  name: reviews
  labels:
    kiali_wizard: request_routing
spec:
  http:
    - route:
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v1
          weight: 100
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v2
          weight: 0
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v3
          weight: 0
      match:
        - headers:
            V1:
              regex: ^.*$
    - route:
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v1
          weight: 0
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v2
          weight: 100
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v3
          weight: 0
      match:
        - headers:
            V2:
              regex: ^.*$
    - route:
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v1
          weight: 0
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v2
          weight: 0
        - destination:
            host: reviews.default.svc.cluster.local
            subset: v3
          weight: 100
      match:
        - headers:
            V3:
              regex: ^.*$
  hosts:
    - reviews.default.svc.cluster.local
  gateways: ~

---

